### ISSUE TITLE
[Artist] Seeing visual reminders if any of my painting photo lacks mandatory descriptions

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/artfolo#20]
As an artist, I want to see visual reminders if any of my painting photo lacks mandatory descriptions

**Comment by nguyenductoan** [comment]
Currently, i see that reminders works fine when painting photo lacks mandatory descriptions.
![screenshot-localhost 3000 2016-02-01 16-20-24](https://cloud.githubusercontent.com/assets/10071833/12713235/00440fb0-c900-11e5-8eec-ccd8fdb18049.png)
Are these reminders need to change style? And what style need to be changed to?

**Comment by irene-ng** [comment]
A simple icon to indicate it and tooltip to tell user that they need to fill in information

**Comment by nguyenductoan** [comment]
As the picture above, it tell exactly error for user, so addition icon is all user need? is it right? @irene-ng

**Comment by irene-ng** [comment]
Yes, we will add a simple icon for all error message.
