### ISSUE TITLE
[User] Shorter length landing page with 2 sections that fit into single view

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/artfolo#5]
I want to see a shorter length landing page with 2 sections that fit into single view so that I don’t need to scroll down

**Comment by irene-ng** [comment]
![artfolo landing page](https://cloud.githubusercontent.com/assets/16044171/12635967/6162688e-c5bb-11e5-8dc6-d4d3482b3038.png)

**Comment by maggie1994** [comment]
done
