### ISSUE TITLE
[User] Seeing a better art listing page

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/artfolo#6]
I want to see a better art listing page

**Comment by irene-ng** [comment]
![artfolo gallery category](https://cloud.githubusercontent.com/assets/16044171/12635974/75be86c8-c5bb-11e5-98b8-852f53a473b7.png)
![artfolo photo showcase](https://cloud.githubusercontent.com/assets/16044171/12635975/75d333d4-c5bb-11e5-9e00-9f956996f93f.png)

**Comment by maggie1994** [comment]
done
